export const obj = {
  arr: [
    'icon-tag-subscipt',
    'icon-chart-pie-alt',
    'icon-structured-data',
    'icon-drag',
    'icon-vector',
    'icon-ellipsis-vertical',
    'icon-NEW-copy ',
    'icon-gallery-view',
    'icon-HOT-copy',
    'icon-WIFI',
    'icon-home',
    'icon-bug-report',
    'icon-monitoring',
    'icon-qrcode',
    'icon-diagnose',
    'icon-scan',
    'icon-loading',
    'icon-cut',
    'icon-Directory-tree',
    'icon-gift',
    'icon-application',
    'icon-link',
    'icon-applicationgroup',
    'icon-poweroff',
    'icon-key',
    'icon-safety-certificate',
    'icon-supervise',
    'icon-tag-subscipt',
    'icon-chart-pie-alt',
    'icon-chart-relation',
    'icon-chart-scatter-plot',
    'icon-chart-area',
    'icon-chart-line',
    'icon-chart-bar',
    'icon-display-code',
    'icon-display-arrow-right',
    'icon-display-arrow-left',
    'icon-laptop-error',
    'icon-laptop-check',
    'icon-laptop',
    'icon-mobile-error',
    'icon-mobile-check',
    'icon-mobile-alt',
    'icon-aliwangwang',
    'icon-nail',
    'icon-nail-fixed',
    'icon-edit',
    'icon-dollar',
    'icon-transanction',
    'icon-filter-fill',
    'icon-all-fill',
    'icon-databaseplus-fill',
    'icon-database-fill',
    'icon-commentlines-fill',
    'icon-commentdots-fill',
    'icon-paperplane-fill',
    'icon-eyeslash-fill',
    'icon-eye-fill',
    'icon-lightbulb-fill',
    'icon-flag-fill',
    'icon-tag-fill',
    'icon-position-fill',
    'icon-location-fill',
    'icon-map-fill',
    'icon-inboxin-fill',
    'icon-box-fill',
    'icon-databaseset-fill',
    'icon-layergroup-fill',
    'icon-cry-fill',
    'icon-smile-fill',
    'icon-unlock-fill',
    'icon-lock-fill',
    'icon-alignright-fill',
    'icon-alignleft-fill',
    'icon-borderbottom-fill',
    'icon-bordertop-fill',
    'icon-aligncenter-fill',
    'icon-borderverticle-fill',
    'icon-piccenter-fill',
    'icon-picside-fill',
    'icon-folderopen-fill',
    'icon-folderplus-fill',
    'icon-folder-fill',
    'icon-file-SQL',
    'icon-fileplus-fill',
    'icon-file-fill',
    'icon-copy-fill',
    'icon-headset-fill',
    'icon-phone-fill',
    'icon-pausecircle-fill',
    'icon-stopcircle-fill',
    'icon-playcircle-fill',
    'icon-delete-fill',
    'icon-picture-fill',
    'icon-mail-fill',
    'icon-heart-fill',
    'icon-collection-fill',
    'icon-user-group-fill',
    'icon-userplus-fill',
    'icon-user-fill',
    'icon-cog-fill',
    'icon-clock-fill',
    'icon-calendaralt-fill',
    'icon-clouddownload-fill',
    'icon-cloudupload-fill',
    'icon-exchange-fill',
    'icon-info-circle-fill',
    'icon-question-circle-fill',
    'icon-exclamationcircle-f',
    'icon-minus-circle-fill',
    'icon-plus-circle-fill',
    'icon-times-circle-fill',
    'icon-check-circle-fill',
    'icon-compressalt-fill',
    'icon-expandalt-fill',
    'icon-filter',
    'icon-all',
    'icon-database-plus',
    'icon-database',
    'icon-comment-lines',
    'icon-comment-dots',
    'icon-paper-plane',
    'icon-eye-slash',
    'icon-eye',

    'icon-lightbulb',
    'icon-flag',
    'icon-tag',
    'icon-position',
    'icon-location',
    'icon-map',
    'icon-inbox-in',
    'icon-box',
    'icon-database-set',
    'icon-layer-group',
    'icon-wind-cry',
    'icon-wind-smile',
    'icon-unlock',
    'icon-lock',
    'icon-align-right',
    'icon-align-left',
    'icon-border-bottom',
    'icon-border-top',
    'icon-align-center',
    'icon-border-verticle',
    'icon-pic-center',
    'icon-pic-side',
    'icon-folder-open',
    'icon-folder-plus',
    'icon-folder',
    'icon-file-SQL1',
    'icon-file-plus',
    'icon-file',
    'icon-copy',
    'icon-headset',
    'icon-phone',
    'icon-pausecircle',
    'icon-stopcircle',
    'icon-playcircle',
    'icon-delete',
    'icon-picture',
    'icon-mail',
    'icon-like',
    'icon-collection',
    'icon-user-group',
    'icon-account-plus',
    'icon-account',
    'icon-cog',
    'icon-clock',
    'icon-calendar-alt',
    'icon-clouddownload',
    'icon-cloudupload',
    'icon-exchange',
    'icon-info-circle',
    'icon-question-circle',
    'icon-exclamation-circle',
    'icon-minus-circle',
    'icon-plus-circle',
    'icon-times-circle',
    'icon-check-circle',
    'icon-compress-alt',
    'icon-expand-alt',
    'icon-ban',
    'icon-minus',
    'icon-plus',
    'icon-times',
    'icon-check',
    'icon-search-minus',
    'icon-search-plus',
    'icon-search',
    'icon-reply',
    'icon-undo',
    'icon-redo',
    'icon-external-link',
    'icon-arrows-alt',
    'icon-indent',
    'icon-outdent',
    'icon-sort-line',
    'icon-switch',
    'icon-wind-descending',
    'icon-wind-ascending',
    'icon-download',
    'icon-upload',
    'icon-arrow-to-bottom',
    'icon-arrow-to-top',
    'icon-long-arrow-down',
    'icon-long-arrow-up',
    'icon-arrow-right',
    'icon-arrow-left',
    'icon-sort',
    'icon-sort-down',
    'icon-sort-up',
    'icon-caret-right',
    'icon-caret-left',
    'icon-arrows-v',
    'icon-angle-double-down',
    'icon-angle-double-up',
    'icon-angle-double-right',
    'icon-angle-double-left',
    'icon-angle-down',
    'icon-angle-up',
    'icon-angle-right',
    'icon-angle-left',
    'icon-paperclip',
    'icon-connection',
    'icon-training',
    'icon-process',
    'icon-news',
    'icon-save',
    'icon-print',
    'icon-new-releases',
    'icon-release',
    'icon-alert',
    'icon-backspace',
    'icon-gem',
    'icon-integral',
    'icon-star-circle',
    'icon-user-circle',
    'icon-cloud-machine-fill',
    'icon-cloud-machine',
    'icon-terminal-fill',
    'icon-terminal',
    'icon-shopping-cart-fill',
    'icon-resource',
    'icon-rank',
    'icon-sync-alt',
    'icon-compass',
    'icon-arrow-alt-from-top',
    'icon-arrow-alt-from-botto',
    'icon-menu',
    'icon-icon-drag',
    'icon-early-warning',
    'icon-share',
    'icon-share1',
    'icon-management-',
    'icon-accesskeys',
    'icon-arrow-sortdown-smal',
    'icon-minus-square-fill',
    'icon-plus-square-fill',
    'icon-minus-square',
    'icon-plus-square',
    'icon-stepmode',
    'icon-scrollingmode',
    'icon-shoppingcart',
    'icon-waiting-fill',
    'icon-waiting',
    'icon-right-arrow-rect',
    'icon-left-arrow-rect',
    'icon-bell',
  ]
};
export const dialogParams = {
  arr: [
    {
      name: 'visible',
      type: 'Boolean',
      explain: '控制 Dialog 是否可见',
      default: 'false'
    },
    {
      name: 'title',
      type: 'String',
      explain: '组件标题',
      default: '标题'
    },
    {
      name: 'content',
      type: 'HTML | String',
      explain: '组件内容',
      default: '需用户填写'
    },
    {
      name: 'okText',
      type: 'String',
      explain: '确认按钮消息',
      default: 'ok'
    },
    {
      name: 'ok',
      type: 'Function',
      explain: '确认按钮回调',
      default: '无'
    },
    {
      name: 'cancelText',
      type: 'String',
      explain: '取消按钮消息',
      default: 'cancel'
    },
    {
      name: 'cancel',
      type: 'Function',
      explain: '取消按钮回调',
      default: '无'
    },
  ]
};
export const buttonParams = {
  arr: [
    {
      name: 'theme',
      type: 'String',
      explain: '按钮类型',
      default: '无'
    },
    {
      name: 'size',
      type: 'String',
      explain: '按钮大小',
      default: '无'
    },
    {
      name: 'level',
      type: 'String',
      explain: '按钮级别',
      default: '无'
    },
    {
      name: 'color',
      type: 'String',
      explain: '按钮颜色',
      default: '无'
    },
    {
      name: 'disabled',
      type: 'Boolean',
      explain: '按钮是否可以操作',
      default: '无'
    },
  ]
};
